### ISSUE TITLE
Pipe character (|) create issue working with table.

### ISSUE THREAD

**Issue by asonu0917** [steven-kraft/obsidian-markdown-furigana#11]
The pipe character (|) is conflicted with md table, creating display issue.
![image](https://user-images.githubusercontent.com/18055333/154792563-211a9282-95da-4aaf-8534-3fbb06d877c1.png)
![image](https://user-images.githubusercontent.com/18055333/154792573-2e15c158-aa5d-4408-a325-15fdd4b24ea1.png)

**Comment by steven-kraft** [comment]
Sorry for the late response. I think putting a backslash before each pipe used for furigana should solve the issue.

**Comment by asonu0917** [comment]
Thanks, it is working.
