### ISSUE TITLE
Adding all CJK characters and punctuation

### ISSUE THREAD

**Issue by simonomi** [steven-kraft/obsidian-markdown-furigana#14]
I believe it's beneficial to change the following line:
```typescript
const REGEXP = /{((?:[\u4E00-\u9FFFㄅ-ㄩぁ-んァ-ンー〇])+)((?:\|[^ -\/{-~:-@\[-`]*)+)}/gm
```
to:
```typescript
const REGEXP = /{((?:[\u2E80-\uA4CF\uFF00-\uFFEF])+)((?:\|[^ -\/{-~:-@\[-`]*)+)}/gm;
```

The regex would then include the following unicode blocks:
> Supplemental Punctuation, CJK Radicals Supplement, Kangxi Radicals, Ideographic Description Characters, CJK Symbols and Punctuation, Hiragana, Katakana, Bopomofo, Hangul Compatibility Jamo, Kanbun, Bopomofo Extended, CJK Strokes, Katakana Phonetic Extensions, Enclosed CJK Letters and Months, CJK Compatibility, CJK Unified Ideographs Extension A, Yijing Hexagram Symbols, CJK Unified Ideographs, Yi Syllables, Yi Radicals, and Halfwidth and Fullwidth Forms

(see [wikipedia](https://en.wikipedia.org/wiki/Unicode_block))

In addition to simplifying the regex, this adds a ton of useful characters and punctuation (fixing #12).

**Comment by steven-kraft** [comment]
Thank you! Just updated this in v1.2.4

Fixes #12
