### ISSUE TITLE
Issue with {|} approach rendering not full line

### ISSUE THREAD

**Issue by dwassem** [steven-kraft/obsidian-markdown-furigana#2]
Hi, 
Thank you very much for your plugin. It is extremely helpful.
One issue I have is that the {|} approach does not properly render - it removes the rest of the content of the row. The \<ruby\> approach renders properly.
I.e.,:

![image](https://user-images.githubusercontent.com/6986678/117921581-ef9de480-b32b-11eb-95bc-527ed48a87c9.png)

Is there any workaround to this?

Thanks,
Daniel

**Comment by emisjerry** [comment]
Here is another problem:

![image](https://user-images.githubusercontent.com/131511/117955860-0f90d080-b34b-11eb-833d-2f8b6961795b.png)

**Comment by steven-kraft** [comment]
Thanks for pointing this out, should be fixed now with the latest release (1.1.2)
