### ISSUE TITLE
Multi-line rendering not working?

### ISSUE THREAD

**Issue by lunakunada** [steven-kraft/obsidian-markdown-furigana#3]
I have installed the latest version plugin.

It seems like there are some rendering problem in multi-line situation.
Here are some screen capture.

![Untitled-1](https://user-images.githubusercontent.com/33832268/118062571-c59aff80-b3c9-11eb-89c4-e55b3158ff3d.jpg)

**Comment by steven-kraft** [comment]
Thanks for pointing that out, I should have a fix for that soon!

**Comment by steven-kraft** [comment]
This should be fixed now as of the latest release (1.1.3) https://github.com/steven-kraft/obsidian-markdown-furigana/commit/4ccc79a9b6ddc49a5e8c940dc0dffa09b3404a88
