### ISSUE TITLE
[Enhancement] Used for English phonetic symbol?

### ISSUE THREAD

**Issue by emisjerry** [steven-kraft/obsidian-markdown-furigana#6]
Ruby is for Asian characters, but could it be used for English phonetic symbol?
![image](https://user-images.githubusercontent.com/131511/118284269-d307d500-b502-11eb-8a4f-a7b31dfb6e6d.png)

There're two common used phonetic symbol: KK phonetic symbol and DJ phonetic symbol.

**Comment by MILKMILKKING** [comment]
Can you use CSS to achieve what you see is what you get? This reduces the impact on the content in the preview state.THX!

**Comment by steven-kraft** [comment]
> Ruby is for Asian characters, but could it be used for English phonetic symbol?
> ![image](https://user-images.githubusercontent.com/131511/118284269-d307d500-b502-11eb-8a4f-a7b31dfb6e6d.png)
> 
> There're two common used phonetic symbol: KK phonetic symbol and DJ phonetic symbol.

Hmmm, I would be interested in considering an update that does this if there was a clean way to line up the phonetic symbols with the syllables they represent. As it is now, the plugin separates the first section by character, so I would have to come up with a new way to separate subsections.

**Comment by steven-kraft** [comment]
> Can you use CSS to achieve what you see is what you get? This reduces the impact on the content in the preview state.THX!

Please don't post new issues as comments to unrelated issues.

I don't really think CSS (alone) could achieve this. If you have some sort of design for how this would work, I'd be open to implementing it.
