### ISSUE TITLE
Internal Links

### ISSUE THREAD

**Issue by langtextic** [steven-kraft/obsidian-markdown-furigana#7]
Would be great if it works with internal links
Now {[[韓國]]|한국} doesn’t render properly, but <ruby>[[韓國]]<rt>한국</rt></ruby> works

**Comment by steven-kraft** [comment]
Hello!

It should work if you do it like this:
```
[[韓國|{韓國|한국}]]
```

**Comment by langtextic** [comment]
thanks! works perfectly!
