### ISSUE TITLE
Character “ー” caused a bug

### ISSUE THREAD

**Issue by doraamy** [steven-kraft/obsidian-markdown-furigana#9]
Character “ー” caused a bug and couldn’t be parsed correctly:

![2D8E9134-B973-47DC-A809-5744CDB2AB5C](https://user-images.githubusercontent.com/22643236/150285482-eac55c07-067e-4154-b42f-9030f8fcf9ad.jpeg)

**Comment by steven-kraft** [comment]
Thanks for pointing this out! Fixed in v1.2.1
